
#include <samd21.h>


void init_uart(){
    SERCOM0->USART.CTRLA.reg = SERCOM_USART_CTRLA_DORD |
        SERCOM_USART_CTRLA_RXPO(0x1) |
        SERCOM_USART_CTRLA_TXPO(0x0) |
        SERCOM_USART_CTRLA_SAMPR(0x0)|
        SERCOM_USART_CTRLA_RUNSTDBY |
        SERCOM_USART_CTRLA_MODE_USART_INT_CLK ;

    SERCOM3->USART.BAUD.reg = baud_value;

    SERCOM3->USART.CTRLB.reg = SERCOM_USART_CTRLB_CHSIZE(0x0) |
        SERCOM_USART_CTRLB_TXEN |
        SERCOM_USART_CTRLB_RXEN ;

    while(SERCOM3->USART.SYNCBUSY.bit.CTRLB);

    system_interrupt_enable(SERCOM3_IRQn);

    SERCOM0->USART.INTENSET.reg = SERCOM_USART_INTFLAG_RXC;

    SERCOM0->USART.CTRLA.reg |= SERCOM_USART_CTRLA_ENABLE;

    while(SERCOM0->USART.SYNCBUSY.reg & SERCOM_USART_SYNCBUSY_ENABLE)
}